import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex">
          <aside className="w-64 border-r border-black/[.08] dark:border-white/[.145] bg-background text-foreground">
            <div className="p-4">
              <nav className="flex flex-col gap-2">
                <Link
                  href="/ledger"
                  className="px-3 py-2 rounded-md hover:bg-black/[.05] dark:hover:bg-white/[.06] font-medium"
                >
                  Кредит | Дебит
                </Link>
              </nav>
            </div>
          </aside>
          <main className="flex-1 p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
